#!/bin/bash
# morning-review.sh - Daily morning review of system logs
# Runs at 7:00 AM, analyzes previous 24h of logs, generates report

set -e

LOG_DIR="/root/.openclaw/workspace/logs"
MEMORY_DIR="/root/.openclaw/workspace/memory"
LOG_FILE="$LOG_DIR/system.log"
TEMPLATE_FILE="$MEMORY_DIR/morning-review-template.md"
DISCORD_CHANNEL="#alerts"

# Get today's date
TODAY=$(date +"%Y-%m-%d")
YESTERDAY=$(date -d "yesterday" +"%Y-%m-%d")
REPORT_FILE="$MEMORY_DIR/morning-review-$TODAY.md"

# Ensure directories exist
mkdir -p "$MEMORY_DIR"

# Optional structured logging + rotate (best-effort)
LOG_SYSTEM="/root/.openclaw/workspace/scripts/log-system.sh"
if [ -x "$LOG_SYSTEM" ]; then
  "$LOG_SYSTEM" rotate >/dev/null 2>&1 || true
  "$LOG_SYSTEM" log CRON_JOB INFO "morning-review" "Morning review started" "{\"report_date\": \"$TODAY\"}" || true
fi

echo "🌅 Morning Review - $TODAY"
echo "=========================="
echo ""

# Check if log file exists
if [ ! -f "$LOG_FILE" ]; then
    echo "⚠️  No system log found at $LOG_FILE"
    echo "   Creating empty report..."
    
    cat > "$REPORT_FILE" << EOF
# Morning Review - $TODAY

**Generated:** $(date +"%Y-%m-%d %H:%M:%S %Z")

## Summary
No system logs found. This may be the first day of logging.

## Action Items
- [ ] Verify logging system is properly integrated
- [ ] Check that log-system.sh is being called by system components

---
*This report was automatically generated by morning-review.sh*
EOF
    
    echo "✓ Report created: $REPORT_FILE"
    exit 0
fi

# Calculate cutoff timestamp (24 hours ago)
CUTOFF_EPOCH=$(date -d "24 hours ago" +%s)
CUTOFF_DATE=$(date -d "24 hours ago" +"%Y-%m-%dT%H:%M:%SZ")

echo "📊 Analyzing logs from last 24 hours..."
echo "   Cutoff: $CUTOFF_DATE"
echo ""

# Extract error events using jq
ERROR_EVENTS=$(jq -c --argjson cutoff "$CUTOFF_EPOCH" '
    select((.epoch | tonumber? // 0) >= $cutoff) |
    select(.severity == "ERROR" or .severity == "CRITICAL" or .event_type == "ALERT")
' "$LOG_FILE" 2>/dev/null || echo "")

# Count total events in period
TOTAL_EVENTS=$(jq -c --argjson cutoff "$CUTOFF_EPOCH" 'select((.epoch | tonumber? // 0) >= $cutoff)' "$LOG_FILE" 2>/dev/null | wc -l | tr -d ' ')
ERROR_COUNT=$(printf '%s\n' "$ERROR_EVENTS" | awk 'NF{count++} END{print count+0}')

echo "📈 Statistics:"
echo "   Total events (24h): $TOTAL_EVENTS"
echo "   Error/Alert events: $ERROR_COUNT"
echo ""

# If no errors, create a healthy report
if [ "$ERROR_COUNT" -eq 0 ] || [ -z "$ERROR_EVENTS" ]; then
    echo "✅ No errors found in the last 24 hours!"
    
    cat > "$REPORT_FILE" << EOF
# Morning Review - $TODAY

**Generated:** $(date +"%Y-%m-%d %H:%M:%S %Z")
**Period:** Last 24 hours (since $CUTOFF_DATE)

## 📊 Summary

| Metric | Value |
|--------|-------|
| Total Events | $TOTAL_EVENTS |
| Errors | 0 |
| Alerts | 0 |
| System Health | ✅ Healthy |

## ✅ All Systems Operational

No errors, failures, or alerts detected in the last 24 hours.

### Event Breakdown
$(jq -s --argjson cutoff "$CUTOFF_EPOCH" '
    [.[] | select((.epoch | tonumber? // 0) >= $cutoff)] |
    group_by(.event_type) |
    map("- **\(.[0].event_type)**: \(length)") |
    join("\n")
' "$LOG_FILE" 2>/dev/null || echo "No events to categorize")

## 📝 Notes
- System is operating normally
- No action items required

---
*This report was automatically generated by morning-review.sh*
EOF
    
    echo "✓ Healthy report created: $REPORT_FILE"
    exit 0
fi

# Analyze errors by category
echo "🔍 Categorizing errors..."

# Group errors by source
ERRORS_BY_SOURCE=$(echo "$ERROR_EVENTS" | jq -s '
    group_by(.source) |
    map({source: .[0].source, count: length, events: .}) |
    sort_by(-.count)
' 2>/dev/null || echo "[]")

# Group errors by type
ERRORS_BY_TYPE=$(echo "$ERROR_EVENTS" | jq -s '
    group_by(.event_type) |
    map({type: .[0].event_type, count: length}) |
    sort_by(-.count)
' 2>/dev/null || echo "[]")

# Extract unique error messages for analysis
UNIQUE_ERRORS=$(echo "$ERROR_EVENTS" | jq -r '.message' 2>/dev/null | sort | uniq -c | sort -rn | head -10)

# Identify code-related errors (for fix proposals)
CODE_ERRORS=$(echo "$ERROR_EVENTS" | jq -c '
    select(.message | test("code|script|function|module|syntax|compile|import|exception|traceback"; "i")) or
    select(.context.error_details | test("code|script|function|module|syntax|compile|import|exception|traceback"; "i"))
' 2>/dev/null || echo "")

CODE_ERROR_COUNT=$(printf '%s\n' "$CODE_ERRORS" | awk 'NF && !/^\[?\]$/ {count++} END{print count+0}')

echo "   Errors by source: $(echo "$ERRORS_BY_SOURCE" | jq 'length')"
echo "   Code-related errors: $CODE_ERROR_COUNT"
echo ""

# Generate fix proposals for code errors
generate_fix_proposals() {
    local error_json="$1"
    
    echo "$error_json" | jq -r '
        .[] |
        "### Error: \(.message[:100])\n\n" +
        "**Source:** \(.source)\n" +
        "**Type:** \(.event_type)\n" +
        "**Timestamp:** \(.timestamp)\n\n" +
        (if .context.error_details and .context.error_details != "" and .context.error_details != "null" then
            "**Details:** \(.context.error_details[:200])\n\n"
        else "" end) +
        "#### Suggested Fix:\n" +
        (if (.message | test("permission|denied|unauthorized"; "i")) then
            "- Check file permissions and user access rights\n" +
            "- Verify API keys or credentials are valid\n" +
            "- Review security policies and access controls"
        elif (.message | test("connection|timeout|network|unreachable"; "i")) then
            "- Verify network connectivity\n" +
            "- Check if the target service is running\n" +
            "- Review firewall rules and security groups\n" +
            "- Increase timeout values if appropriate"
        elif (.message | test("file|not found|missing|ENOENT"; "i")) then
            "- Verify the file path is correct\n" +
            "- Check if the file was moved or deleted\n" +
            "- Ensure parent directories exist\n" +
            "- Review file creation logic"
        elif (.message | test("syntax|parse|invalid|malformed"; "i")) then
            "- Review the code syntax\n" +
            "- Check for missing brackets, quotes, or semicolons\n" +
            "- Validate JSON/YAML configuration files\n" +
            "- Use a linter to identify issues"
        elif (.message | test("memory|heap|OOM|out of memory"; "i")) then
            "- Profile memory usage to identify leaks\n" +
            "- Increase memory limits if appropriate\n" +
            "- Optimize data structures and algorithms\n" +
            "- Implement pagination or streaming for large datasets"
        elif (.message | test("disk|space|storage|full"; "i")) then
            "- Clean up old log files and temporary data\n" +
            "- Implement log rotation\n" +
            "- Expand storage capacity\n" +
            "- Archive old data to cold storage"
        else
            "- Review the error context and stack trace\n" +
            "- Check recent code changes\n" +
            "- Search for similar issues in documentation\n" +
            "- Add additional logging to diagnose the issue"
        end) +
        "\n"
    ' 2>/dev/null || echo "Unable to generate fix proposals\n"
}

# Check for critical failures (multiple errors from same source)
CRITICAL_SOURCES=$(echo "$ERRORS_BY_SOURCE" | jq -r '.[] | select(.count >= 3) | .source' 2>/dev/null || echo "")
HAS_CRITICAL=false
if [ -n "$CRITICAL_SOURCES" ]; then
    HAS_CRITICAL=true
    echo "🚨 CRITICAL: Multiple failures detected from: $CRITICAL_SOURCES"
fi

# Generate the report
echo "📝 Generating report..."

cat > "$REPORT_FILE" << EOF
# Morning Review - $TODAY

**Generated:** $(date +"%Y-%m-%d %H:%M:%S %Z")
**Period:** Last 24 hours (since $CUTOFF_DATE)

## 📊 Summary

| Metric | Value |
|--------|-------|
| Total Events | $TOTAL_EVENTS |
| Errors/Alerts | $ERROR_COUNT |
| Code-Related | $CODE_ERROR_COUNT |
| System Health | $([ "$HAS_CRITICAL" = "true" ] && echo "🔴 Critical" || echo "🟡 Attention Needed") |

## 🚨 Error Summary

### By Source
$(echo "$ERRORS_BY_SOURCE" | jq -r '.[] | "- **\(.source)**: \(.count) error(s)"' 2>/dev/null || echo "No data")

### By Type
$(echo "$ERRORS_BY_TYPE" | jq -r '.[] | "- **\(.type)**: \(.count)"' 2>/dev/null || echo "No data")

### Most Common Errors
\`\`\`
$UNIQUE_ERRORS
\`\`\`

EOF

# Add critical alert section if needed
if [ "$HAS_CRITICAL" = "true" ]; then
    cat >> "$REPORT_FILE" << EOF
## 🔴 Critical Issues

The following sources have repeated failures (3+ errors):

$CRITICAL_SOURCES

**Immediate action required.** These may indicate:
- Systemic issues requiring architectural fixes
- Resource exhaustion (memory, disk, connections)
- External dependency failures
- Configuration problems

EOF
fi

# Add detailed error analysis
cat >> "$REPORT_FILE" << EOF
## 🔍 Detailed Error Analysis

EOF

# Add each error with context
if [ -n "$ERROR_EVENTS" ] && ! echo "$ERROR_EVENTS" | grep -q '^\[\]$'; then
    echo "$ERROR_EVENTS" | while read -r line; do
        if [ -z "$line" ] || [ "$line" = "null" ]; then continue; fi
        
        timestamp=$(echo "$line" | jq -r '.timestamp // "unknown"')
        severity=$(echo "$line" | jq -r '.severity // "unknown"')
        event_type=$(echo "$line" | jq -r '.event_type // "unknown"')
        source=$(echo "$line" | jq -r '.source // "unknown"')
        message=$(echo "$line" | jq -r '.message // "unknown"')
        context=$(echo "$line" | jq -c '.context // {}' 2>/dev/null || echo "{}")
        
        echo "### [$severity] $event_type" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "**Time:** $timestamp" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "**Source:** $source" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "**Message:** $message" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        
        if [ "$context" != "{}" ] && [ -n "$context" ]; then
            echo "**Context:**" >> "$REPORT_FILE"
            echo "" >> "$REPORT_FILE"
            echo "\`\`\`json" >> "$REPORT_FILE"
            echo "$context" | jq -r '.' >> "$REPORT_FILE"
            echo "\`\`\`" >> "$REPORT_FILE"
            echo "" >> "$REPORT_FILE"
        fi
    done
else
    echo "No valid error events to analyze" >> "$REPORT_FILE"
fi

# Add fix proposals for code-related errors
if [ "$CODE_ERROR_COUNT" -gt 0 ]; then
    cat >> "$REPORT_FILE" << EOF
## 🔧 Suggested Fixes for Code-Related Errors

$(generate_fix_proposals "$CODE_ERRORS")
EOF
fi

# Add action items
cat >> "$REPORT_FILE" << EOF
## ✅ Action Items

- [ ] Review critical errors above
- [ ] Implement suggested fixes for code-related issues
- [ ] Check system resources (disk, memory, CPU)
- [ ] Verify external dependencies are healthy
- [ ] Update monitoring/alerting if gaps identified

## 📈 Trends

Compare with previous days:
- Check \`$MEMORY_DIR/morning-review-$YESTERDAY.md\` for yesterday's report
- Look for recurring patterns
- Track error rates over time

---
*This report was automatically generated by morning-review.sh*
EOF

echo "✓ Report created: $REPORT_FILE"

# Send to Discord if critical failures found
if [ "$HAS_CRITICAL" = "true" ]; then
    echo ""
    echo "📤 Sending critical alert to Discord..."
    
    # Create a summary message for Discord
    CRITICAL_SUMMARY=$(cat << EOF
🚨 **Critical System Alert - Morning Review**

**Date:** $TODAY
**Errors:** $ERROR_COUNT in last 24h
**Critical Sources:** $CRITICAL_SOURCES

**Top Issues:**
$(echo "$ERRORS_BY_SOURCE" | jq -r '.[:3] | .[] | "- \(.source): \(.count) errors"' 2>/dev/null || echo "- Unable to summarize")

**Report:** $REPORT_FILE

Immediate review required.
EOF
)
    
    # Try to send to Discord (if message tool is available via main agent)
    # This is a placeholder - actual Discord sending would be done by main agent
    echo "⚠️  Discord notification prepared (requires main agent to send):"
    echo "$CRITICAL_SUMMARY"
    
    # Save the Discord message to a file for the main agent to pick up
    DISCORD_ALERT_FILE="$MEMORY_DIR/alerts/discord-critical-$TODAY.txt"
    mkdir -p "$(dirname "$DISCORD_ALERT_FILE")"
    echo "$CRITICAL_SUMMARY" > "$DISCORD_ALERT_FILE"
    echo "✓ Alert saved to: $DISCORD_ALERT_FILE"
fi

echo ""
echo "=========================="
echo "Morning review complete!"
echo "Report: $REPORT_FILE"
[ "$HAS_CRITICAL" = "true" ] && echo "🚨 Critical alert prepared for Discord"
echo ""

if [ -x "$LOG_SYSTEM" ]; then
  "$LOG_SYSTEM" log CRON_JOB INFO "morning-review" "Morning review completed" "{\"report_file\": \"$REPORT_FILE\", \"critical\": $HAS_CRITICAL, \"error_count\": $ERROR_COUNT}" || true
fi
